" VIM config,


"source $VIMRUNTIME/defaults.vim

source ~/.config/nvim/00/setting.vim
source ~/.config/nvim/00/keymap.vim
source ~/.config/nvim/00/autocmd.vim
source ~/.config/nvim/00/cs_forest.vim


